### PR TITLE
#166320284 Set up code climate

### PR DESCRIPTION
**Pull request by frankopkusianwar**
**What does this PR do?**

Adds the repository to codeclimate

**Description of Task to be completed?**

- add the repository to codeclimate
- set the default branch to ch-add-codeclimate-badge-166320284(this will later be set to develop when the PR is merged)
- add the badge to the readme file

**How should this be manually tested?**

- visit the ch-add-codeclimate-badge-16632028 branch on github
- Scroll down to the readme file
- there should be a codeclimate badge displaying the maintainability
- click on the badge to view details on codeclimate

**What are the relevant pivotal tracker stories?**

[#166320284](https://www.pivotaltracker.com/story/show/166320284)

**Screenshots**

codeclimate

### CODE REVIEW

**Comment by NicholusMuwonge** [comment]
Thanks for the beautiful work @frankopkusianwar, however, I think you should add the PT story as a link to enable someone to check it out without going through the hassle of looking for the story. Thanks

**Comment by frankopkusianwar** [comment]
> Thanks for the beautiful work @frankopkusianwar, however, I think you should add the PT story as a link to enable someone to check it out without going through the hassle of looking for the story. Thanks

@NicholusMuwonge that has been updated thanks

**Review by NicholusMuwonge — APPROVED** [review]

**Review by richien — APPROVED** [review]

**Review by sebbss — APPROVED** [review]

**Review by nakatuddesuzan — CHANGES_REQUESTED** [review]
Hello @frankopkusianwar . Kindly squash those commits. A PR should have a single commit. Probably the rebase didn't go well. Kindly look into it

**Comment by NicholusMuwonge** [comment]
> Hello @frankopkusianwar . Kindly squash those commits. A PR should have a single commit. Probably the rebase didn't go well. Kindly look into it

@frankopkusianwar , you could use ```git rebase -i HEAD~3```

**Comment by frankopkusianwar** [comment]
> Hello @frankopkusianwar . Kindly squash those commits. A PR should have a single commit. Probably the rebase didn't go well. Kindly look into it

@nakatuddesuzan I had missed squashing the commits but that is done now

**Comment by frankopkusianwar** [comment]
> > Hello @frankopkusianwar . Kindly squash those commits. A PR should have a single commit. Probably the rebase didn't go well. Kindly look into it
> 
> @frankopkusianwar , you could use `git rebase -i HEAD~3`

@NicholusMuwonge thanks for that, i have successfully squashed

**Comment by nakatuddesuzan** [comment]
This PR has been closed because it is pointing to master yet it has to be pointed to develop. Another PR Is going to be opened pointing to develop by @frankopkusianwar

**Pull request closed without merging**
