### PR TITLE
#166185760 Cache nutrition values for plans

### PR DESCRIPTION
**Pull request by sebbss**
**What does this PR do?**
cache nutrition values after running the GET endpoint for nutrition plans 

**Description of Task to be completed?**

- add function that creates the cache of nutrition values
- add signals to delete the cache when a change is made in Meal, MealItem or Nutrition classes
- write tests for the added functionality

**How should this be manually tested?**

- clone the project on your machine
- setup the project following the instructions in the readme file
- checkout to the branch `ft-cache-nutrition-values-for-plan`
- run the tests using `python manage.py test wger.nutrition.tests.test_nutritional_cache`

**What are the relevant pivotal tracker stories?**

[#166185760](https://www.pivotaltracker.com/story/show/166185760)

### CODE REVIEW

**Review by frankopkusianwar — APPROVED** [review]
good work @sebbss

**Review by NicholusMuwonge — APPROVED** [review]
Thanks, @sebbss  for the nice work, going through the implementation, I understand what you mean but I still can't figure out how this can best be demoed to the Product Owner.

**Comment by NicholusMuwonge** [comment]
> Thanks, @sebbss for the nice work, going through the implementation, I understand what you mean but I still can't figure out how this can best be demoed to the Product Owner.

Also kindly please update the readme to reflect the review app rather than someone needing to clone this repository branch

**Review by richien — APPROVED** [review]
Thank you for the good work @sebbss, though I was a bit unsure about how best to test this feature. I don't believe running the test cases is the best way to verify this functionality but overall, good job.

**Comment by sebbss** [comment]
> Thank you for the good work @sebbss, though I was a bit unsure about how best to test this feature. I don't believe running the test cases is the best way to verify this functionality but overall, good job.

Another way of testing this feature is opening the

> > Thanks, @sebbss for the nice work, going through the implementation, I understand what you mean but I still can't figure out how this can best be demoed to the Product Owner.
> 
> Also kindly please update the readme to reflect the review app rather than someone needing to clone this repository branch

**Pull request merged**
