### PR TITLE
#166185757 Reformat codebase to meet PEP8 conventions

### PR DESCRIPTION
**Pull request by richien**
#### What does this PR do?

Reformat the codebase to satisfy to PEP8 conventions.

#### Description of Task to be completed?

- Used the python package `black` to reformat the project files to PEPE8 standards, for instance, to limit characters on a line to 79 characters.
- Installation of the Flake8 package and added it to the requirements.txt file for testing compliance with the PEP8 standards.
- Add command to `.circleci/config.yml` to enable flake8 checks to be run by CircleCI when testing the build on a PR.

#### How should this be manually tested?

- Create a local instance of the application off this branch following the instructions in the [README](https://github.com/andela/wger-space/blob/master/README.rst) file.
- `cd` into the project root directory, the one that has the `manage.py` file.
- Run the command `flake8 wger` to use flake8 to check to style coding errors and warnings
- A successful test returns a bash prompt with no warnings, failures or errors displayed

#### Any background context you want to provide?

- The following files and folders are excluded from the flake8 style check:
 urls.py, tasks.py, migrations, bower_components, docs, settings
-  Ignored warnings, failures and errors:

- [ ] **F401** imported but unused

- [ ] **W503** line break before binary operator

- [ ] **F811** redefinition of a function

- [ ] **E741** ambiguous variable name

- The above failures, errors, and warnings were ignored because they required refactoring the code structure, which was out of the scope of this task.

#### What are the relevant pivotal tracker stories?

[#166185757](https://www.pivotaltracker.com/story/show/166185757)

#### Screenshots (if appropriate)

- A successful run of the `flake8 wger` command
Screen Shot 2019-05-28 at 11 19 36

### CODE REVIEW

**Comment by NicholusMuwonge** [comment]
Hey @richien, this is good work, locally it functions as described but I would suggest you also add the functionality to your PR description of Circle CI failing if not a success and otherwise if there's a success. This is because it will be the new test of this chore when Circle Ci is integrated into the whole project. Otherwise nice work @richien

**Comment by richien** [comment]
> Hey @richien, this is good work, locally it functions as described but I would suggest you also add the functionality to your PR description of Circle CI failing if not a success and otherwise if there's a success. This is because it will be the new test of this chore when Circle Ci is integrated into the whole project. Otherwise nice work @richien

Thank you @NicholusMuwonge. As I had explained to you in our one on one conversation, I expect that there will be a task to integrate Flake8 style checks into CircleCI, if this task is merged into `develop` before the CircleCI integration. However, in the current scope of this task, I believe that being able to check for styling errors locally before pushing code to GH is just as important which is why the description here is centered around being able to run those checks locally.

**Comment by NicholusMuwonge** [comment]
> > Hey @richien, this is good work, locally it functions as described but I would suggest you also add the functionality to your PR description of Circle CI failing if not a success and otherwise if there's a success. This is because it will be the new test of this chore when Circle Ci is integrated into the whole project. Otherwise nice work @richien
> 
> Thank you @NicholusMuwonge. As I had explained to you in our one on one conversation, I expect that there will be a task to integrate Flake8 style checks into CircleCI, if this task is merged into `develop` before the CircleCI integration. However, in the current scope of this task, I believe that being able to check for styling errors locally before pushing code to GH is just as important which is why the description here is centered around being able to run those checks locally.

Sorry, my bad, I didn't fully understand the task and as per the description, @richien, this works fine.

**Review by NicholusMuwonge — APPROVED** [review]

**Review by frankopkusianwar — CHANGES_REQUESTED** [review]
@richien, since we are having circleCI to automate our testing and development cycles wouldn't it be better to remove the travis.yml file from your branch to avoid the use of travisCI as well

**Comment by richien** [comment]
> @richien, since we are having circleCI to automate our testing and development cycles wouldn't it be better to remove the travis.yml file from your branch to avoid the use of travisCI as well

@frankopkusianwar , thank you for the feedback. The **.travis.yml** file was removed in another task, i.e during the CircleCi integration. I did not remove it from this branch because that has been done in another task and doing so is also out of the scope of this particular task. In any case, it will be removed when this branch **rebases** with the branch in which the file is removed.

**Comment by frankopkusianwar** [comment]
> > @richien, since we are having circleCI to automate our testing and development cycles wouldn't it be better to remove the travis.yml file from your branch to avoid the use of travisCI as well
> 
> @frankopkusianwar , thank you for the feedback. The **.travis.yml** file was removed in another task, i.e during the CircleCi integration. I did not remove it from this branch because that has been done in another task and doing so is also out of the scope of this particular task. In any case, it will be removed when this branch **rebases** with the branch in which the file is removed.

Okay, I think this solves my concern

**Review by frankopkusianwar — APPROVED** [review]

**Review by sebbss — APPROVED** [review]

**Review by nakatuddesuzan — APPROVED** [review]

**Pull request merged**
