### PR TITLE
#166185759 Present deactivated users in gym overview

### PR DESCRIPTION
**Pull request by richien**
#### What does this PR do?

Display active and inactive users separately in the gym overview

#### Description of Task to be completed?

- filter and store active and inactive users in separate lists
- create a template for displaying the inactive users
- add two buttons for navigating between the active and inactive user
 views from the in the gym overview

#### How should this be manually tested?

- Clone this repo and set up the application locally according to the [README](https://github.com/andela/wger-space/blob/ft-display-active-inactive-users-166185759/README.rst) file.
- `cd` into `wger-space`, start the development server and navigate to the web app on `http://127.0.0.1:8000/`
- Create some users in the application that will be deactivated later. Also create a **superuser** using the command `python manage.py createsuperuser` and follow the prompts. 
- Log in to the app as the superuser  and navigate to `http://127.0.0.1:8000/en/user/list`
- Deactivate one of the users using this route `http://127.0.0.1:8000/en/user/{ID}/deactivate`. Replace ID with the id of one of your users. You should have a deactivated user after running that.
- Click on the `Deactivated Users` button to view the inactive users. The default view shows only active users. 

#### Any background context you want to provide?

- There is an issue in displaying the `navigation menu` on the development application. To navigate to the page for this feature, you will need to manually enter the URL above in your browser's address bar.

#### What are the relevant pivotal tracker stories?

[#166185759](https://www.pivotaltracker.com/story/show/166185759)

#### Screenshots (if appropriate)
- Active Users View
Screen Shot 2019-05-31 at 16 42 43

- De-activated Users view
Screen Shot 2019-05-31 at 16 43 03

### CODE REVIEW

**Comment by frankopkusianwar** [comment]
great work @richien, i have been able to login and access the list of active users, however I wanted to know how I can have a deactivated user so that I can check their existance on the inactive user page because currently it is empty

**Comment by richien** [comment]
> great work @richien, i have been able to login and access the list of active users, however I wanted to know how I can have a deactivated user so that I can check their existance on the inactive user page because currently it is empty

Thank you for the review @frankopkusianwar. For test purposes, I manually deactivated the users by changing the `is_active` field to `0` in the `auth_user` table of the sqlite3 local database. This is because the navigation menu is still not rendering on the local application and as such, I have not yet been able to locate the admin view in the app's GUI from which to do this.

**Review by NicholusMuwonge — COMMENTED** [review]
@richien thanks for the nice work, though it's not really necessary at this point, I would recommend that you add your javascript in different files. This makes it easy to debug the code in case of any bugs detected in the future.

**Comment by NicholusMuwonge** [comment]
@richien, please endeavor to update the readme to cater for how to test for deactivation because although everything works fine, testing for deactivated users will be a hustle for those querying tables in the terminals. So I would also recommend that each team Space member get SQLPro for SQLite software tool to view the tables easily and be able to edit easily

**Comment by richien** [comment]
> @richien thanks for the nice work, though it's not really necessary at this point, I would recommend that you add your javascript in different files. This makes it easy to debug the code in case of any bugs detected in the future.

@NicholusMuwonge , thank you for the feedback. This has been implemented.

**Review by NicholusMuwonge — APPROVED** [review]

**Review by sebbss — APPROVED** [review]

**Review by frankopkusianwar — APPROVED** [review]

**Review by nakatuddesuzan — APPROVED** [review]
Goodwork

**Pull request merged**
