### PR TITLE
#166185758 Add Circle CI Integrations

### PR DESCRIPTION
**Pull request by NicholusMuwonge**
#### What does this PR do?
Get Circle CI integrated with Github, Slack, and Coveralls

#### Description of Task to be completed?
- Added Circle Ci as circleci_space to the space integrations channel in Slack
- Pointed Circle CI to the Github branches to check for tests passing and then pass on the report to Coveralls for coverage of the tests written.
- Added badges for Circle CI build and Coveralls to the Readme.

#### How should this be manually tested?
- Check for the circleci_space user in the space integrations Slack channel you will be able to find the changes are being tracked as per the Github pushes.
Screen Shot 2019-05-28 at 16 21 41

- There are badges of the build for Circle CI passing alongside the badge for code coverage for Coveralls. This is well demonstrated in the image below;
Screen Shot 2019-05-28 at 16 25 39

- If a PR is raised and it's conforming to all the checks, something like this should be the displayed result 
Screen Shot 2019-05-28 at 16 49 05

#### Any background context you want to provide?
This is currently testable on the branch ch-circle-ci-integrations-with-slack-166185758 but will be available for every branch off develop once merged.

#### What are the relevant pivotal tracker stories?
[#166185758](https://www.pivotaltracker.com/story/show/166185758)

### CODE REVIEW

**Review by richien — CHANGES_REQUESTED** [review]
Hi @NicholusMuwonge, thank you for your persistence. I know there were a lot of challenges with the setup. I have noticed that there are files appearing in our coverage report that shouldn't have been tested; for instance, the settings file, __init__.py, manage.py as in the screenshot below and some others. Is it possible to exclude these files from the tests? This will most certainly help to improve our test coverage.
Screen Shot 2019-05-28 at 17 11 39

**Review by richien — APPROVED** [review]

**Review by frankopkusianwar — APPROVED** [review]
Great work @NicholusMuwonge, the coverage, circleCI and slack are properly integrated,

**Review by sebbss — APPROVED** [review]

**Comment by nakatuddesuzan** [comment]
Amazing work @NicholusMuwonge . Kindly look at this section `What are the relevant pivotal tracker stories?` In your PR description. You need to add the story link to the story Id.

**Comment by NicholusMuwonge** [comment]
> Amazing work @NicholusMuwonge . Kindly look at this section `What are the relevant pivotal tracker stories?` In your PR description. You need to add the story link to the story Id.

This has been reacted to please, thanks

**Review by nakatuddesuzan — APPROVED** [review]

**Pull request merged**
